version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/app"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/game"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/server"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
