name: Release

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build alpha app
        run: |
          yarn && cd alpha && yarn && yarn generate
          cd ../levels && yarn && yarn build
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Sync files to S3 bucket
        run: |
          cd alpha && aws s3 sync .output/public s3://kernelquest-assets
          cd ../levels && aws s3 sync dist s3://kernelquest-assets/levels
          aws cloudfront create-invalidation --distribution-id E2VRKRRAMLQPM9 --paths "/*"
